baseURL = 'https://yumin.ai/'
languageCode = 'en-us'
title = 'AI Craft'
theme = 'PaperMod'
timeZone               = "America/Los_Angeles"

[pagination]
  disableAliases = false
  pagerSize = 20
 

tags = [
  "ai",
  "人工智能",
  "llm"
]

[params]
    env = "production"
    description = "专注于发布ai相关的内容"
    DateFormat =  "Monday, January 2, 2006"
    ShowAllPagesInArchive = true
    ShowFullTextinRSS = true

  
    [params.homeInfoParams]
        title = "AI Craft"
        content = """
专注于发布ai相关的内容

有事请联系mail#yumin.ai （请将 # 替换为 @）

"""
